---
title: "3D clusters"
author: "Victor Van der Meersch"
date: "31/01/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(ggplot2)
library(data.table)
library(terra)
library(tidyterra)
library(plotly)
library(dplyr)
library(cowplot)


wd <- "C:/Users/vandermeersch/Documents/CEFE/projects/contrast_calibrations"
source(file.path(wd, "scripts", "functions", "read_mean_outputvalue.R"))

simulations <- c("D:/simulations/phenofit/present/expert/fagus_sylvatica/VVanderMeersch",
                 paste0("D:/simulations/phenofit/present/fitted/fagus_sylvatica/paper_data/CMAES/", 
                        c("subset4_rep1", "subset5_rep4", "subset3_rep8", "subset1_rep7")))

thresholds <- c(0.162, 0.785, 0.674, 0.663, 0.803)


```

## Expert calibration

```{r expert}
c <- 1

surv <- rast(read_mean_outputvalue(simulations[c], 
                                   years = c(1970:2000), model = "PHENOFIT", output_var = "Survival")[,c(2,1,3)])
fruitind <- rast(read_mean_outputvalue(simulations[c], 
                                       years = c(1970:2000), model = "PHENOFIT", output_var = "FruitIndex")[,c(2,1,3)])
matind <- rast(read_mean_outputvalue(simulations[c],
                                     years = c(1970:2000), model = "PHENOFIT", output_var = "MaturationIndex")[,c(2,1,3)])
fitness <- rast(read_mean_outputvalue(simulations[c], 
                                     years = c(1970:2000), model = "PHENOFIT", output_var = "Fitness")[,c(2,1,3)])
  
indices <- c(surv, fruitind, matind)
  
presence <- rast(readRDS("D:/species/processed/fagus_sylvatica/fagus_sylvatica_presabs.rds"))
presence[presence == 0] <- NA
fitnessmask <- fitness
fitnessmask[fitnessmask >= thresholds[c]] <- NA
presence <- crop(presence, fitnessmask)
fitnessmask <- crop(fitnessmask, presence)
presencemask <- mask(presence, fitnessmask)
  
ggplot() +
    geom_spatraster(data = ifel(fitness >= 0, 1, NA), alpha = 0.2, show.legend = FALSE) +
    geom_spatraster(data = ifel(fitness >= thresholds[c], 1, NA), alpha = 0.2, show.legend = FALSE) +
    scale_fill_continuous(na.value = "transparent") +
    geom_spatraster_rgb(data = mask(crop(1-indices, presencemask), presencemask)*255) +
    theme_void()

indices_falseabsences <- as.data.frame(mask(crop(indices, presencemask), presencemask), xy = TRUE)
names(indices_falseabsences) <- c("lon", "lat", "surv", "fruitind", "matind")

df = indices_falseabsences
df$cluster = factor(kmeans(df[,c("surv", "fruitind", "matind")],3)$cluster)

p <- plot_ly(df, x=~surv, y=~fruitind, 
             z=~matind, color= ~I(rgb(1-surv, 1-fruitind, 1-matind))) %>%
  add_markers(size=1.5)
p

p <- plot_ly(df, x=~surv, y=~fruitind, 
             z=~matind, color=~cluster,
             colors = c("#95d2bc", "#fcaf96", "#afc2da")) %>%
  add_markers(size=1.5)
p

ggplot(data = df) +
  geom_spatraster(data = ifel(fitness >= 0, 1, NA), alpha = 0.2, show.legend = FALSE) +
  scale_fill_continuous(na.value = "transparent") +
  geom_point(aes(x = lon, y = lat, color = cluster), size = 0.4) +
  scale_color_manual(values = c("#95d2bc", "#fcaf96", "#afc2da")) +
  theme_void() +
  theme(legend.position = "none")

p1 <- ggplot(data = df) +
  geom_point(aes(x = surv, y = fruitind, color = cluster), alpha = 0.5) +
  scale_color_manual(values = c("#95d2bc", "#fcaf96", "#afc2da")) +
  theme_minimal() +
  theme(legend.position = "none")

p2 <- ggplot(data = df) +
  geom_point(aes(x = fruitind, y = matind, color = cluster), alpha = 0.5) +
  scale_color_manual(values = c("#95d2bc", "#fcaf96", "#afc2da")) +
  theme_minimal() +
  theme(legend.position = "none")

plot_grid(p1, p2, ncol = 2)

```


## Best calibration - subset4_rep1
```{r cmaes1}
c <- 2

surv <- rast(read_mean_outputvalue(simulations[c], 
                                   years = c(1970:2000), model = "PHENOFIT", output_var = "Survival")[,c(2,1,3)])
fruitind <- rast(read_mean_outputvalue(simulations[c], 
                                       years = c(1970:2000), model = "PHENOFIT", output_var = "FruitIndex")[,c(2,1,3)])
matind <- rast(read_mean_outputvalue(simulations[c],
                                     years = c(1970:2000), model = "PHENOFIT", output_var = "MaturationIndex")[,c(2,1,3)])
fitness <- rast(read_mean_outputvalue(simulations[c], 
                                     years = c(1970:2000), model = "PHENOFIT", output_var = "Fitness")[,c(2,1,3)])
  
indices <- c(surv, fruitind, matind)
  
presence <- rast(readRDS("D:/species/processed/fagus_sylvatica/fagus_sylvatica_presabs.rds"))
presence[presence == 0] <- NA
fitnessmask <- fitness
fitnessmask[fitnessmask >= thresholds[c]] <- NA
presence <- crop(presence, fitnessmask)
fitnessmask <- crop(fitnessmask, presence)
presencemask <- mask(presence, fitnessmask)
  
ggplot() +
    geom_spatraster(data = ifel(fitness >= 0, 1, NA), alpha = 0.2, show.legend = FALSE) +
    geom_spatraster(data = ifel(fitness >= thresholds[c], 1, NA), alpha = 0.2, show.legend = FALSE) +
    scale_fill_continuous(na.value = "transparent") +
    geom_spatraster_rgb(data = mask(crop(1-indices, presencemask), presencemask)*255) +
    theme_void()

indices_falseabsences <- as.data.frame(mask(crop(indices, presencemask), presencemask), xy = TRUE)
names(indices_falseabsences) <- c("lon", "lat", "surv", "fruitind", "matind")

df = indices_falseabsences
df$cluster = factor(kmeans(df[,c("surv", "fruitind", "matind")],3)$cluster)

p <- plot_ly(df, x=~surv, y=~fruitind, 
             z=~matind, color= ~I(rgb(1-surv, 1-fruitind, 1-matind))) %>%
  add_markers(size=1.5)
p

p <- plot_ly(df, x=~surv, y=~fruitind, 
             z=~matind, color=~cluster,
             colors = c("#95d2bc", "#fcaf96", "#afc2da")) %>%
  add_markers(size=1.5)
p

ggplot(data = df) +
  geom_spatraster(data = ifel(fitness >= 0, 1, NA), alpha = 0.2, show.legend = FALSE) +
  scale_fill_continuous(na.value = "transparent") +
  geom_point(aes(x = lon, y = lat, color = cluster), size = 0.4) +
  scale_color_manual(values = c("#95d2bc", "#fcaf96", "#afc2da")) +
  theme_void()

p1 <- ggplot(data = df) +
  geom_point(aes(x = surv, y = fruitind, color = cluster), alpha = 0.5) +
  scale_color_manual(values = c("#95d2bc", "#fcaf96", "#afc2da")) +
  theme_minimal() +
  theme(legend.position = "none")

p2 <- ggplot(data = df) +
  geom_point(aes(x = fruitind, y = matind, color = cluster), alpha = 0.5) +
  scale_color_manual(values = c("#95d2bc", "#fcaf96", "#afc2da")) +
  theme_minimal() +
  theme(legend.position = "none")

plot_grid(p1, p2, ncol = 2)

```

## subset5_rep4
```{r cmaes2}
c <- 3

surv <- rast(read_mean_outputvalue(simulations[c], 
                                   years = c(1970:2000), model = "PHENOFIT", output_var = "Survival")[,c(2,1,3)])
fruitind <- rast(read_mean_outputvalue(simulations[c], 
                                       years = c(1970:2000), model = "PHENOFIT", output_var = "FruitIndex")[,c(2,1,3)])
matind <- rast(read_mean_outputvalue(simulations[c],
                                     years = c(1970:2000), model = "PHENOFIT", output_var = "MaturationIndex")[,c(2,1,3)])
fitness <- rast(read_mean_outputvalue(simulations[c], 
                                     years = c(1970:2000), model = "PHENOFIT", output_var = "Fitness")[,c(2,1,3)])
  
indices <- c(surv, fruitind, matind)
  
presence <- rast(readRDS("D:/species/processed/fagus_sylvatica/fagus_sylvatica_presabs.rds"))
presence[presence == 0] <- NA
fitnessmask <- fitness
fitnessmask[fitnessmask >= thresholds[c]] <- NA
presence <- crop(presence, fitnessmask)
fitnessmask <- crop(fitnessmask, presence)
presencemask <- mask(presence, fitnessmask)
  
ggplot() +
    geom_spatraster(data = ifel(fitness >= 0, 1, NA), alpha = 0.2, show.legend = FALSE) +
    geom_spatraster(data = ifel(fitness >= thresholds[c], 1, NA), alpha = 0.2, show.legend = FALSE) +
    scale_fill_continuous(na.value = "transparent") +
    geom_spatraster_rgb(data = mask(crop(1-indices, presencemask), presencemask)*255) +
    theme_void()

indices_falseabsences <- as.data.frame(mask(crop(indices, presencemask), presencemask), xy = TRUE)
names(indices_falseabsences) <- c("lon", "lat", "surv", "fruitind", "matind")

df = indices_falseabsences
df$cluster = factor(kmeans(df[,c("surv", "fruitind", "matind")],3)$cluster)

p <- plot_ly(df, x=~surv, y=~fruitind, 
             z=~matind, color= ~I(rgb(1-surv, 1-fruitind, 1-matind))) %>%
  add_markers(size=1.5)
p

p <- plot_ly(df, x=~surv, y=~fruitind, 
             z=~matind, color=~cluster,
             colors = c("#95d2bc", "#fcaf96", "#afc2da")) %>%
  add_markers(size=1.5)
p

ggplot(data = df) +
  geom_spatraster(data = ifel(fitness >= 0, 1, NA), alpha = 0.2, show.legend = FALSE) +
  scale_fill_continuous(na.value = "transparent") +
  geom_point(aes(x = lon, y = lat, color = cluster), size = 0.4) +
  scale_color_manual(values = c("#95d2bc", "#fcaf96", "#afc2da")) +
  theme_void()

p1 <- ggplot(data = df) +
  geom_point(aes(x = surv, y = fruitind, color = cluster), alpha = 0.5) +
  scale_color_manual(values = c("#95d2bc", "#fcaf96", "#afc2da")) +
  theme_minimal() +
  theme(legend.position = "none")

p2 <- ggplot(data = df) +
  geom_point(aes(x = fruitind, y = matind, color = cluster), alpha = 0.5) +
  scale_color_manual(values = c("#95d2bc", "#fcaf96", "#afc2da")) +
  theme_minimal() +
  theme(legend.position = "none")

plot_grid(p1, p2, ncol = 2)

```


## subset3_rep8
```{r cmaes3}
c <- 4

surv <- rast(read_mean_outputvalue(simulations[c], 
                                   years = c(1970:2000), model = "PHENOFIT", output_var = "Survival")[,c(2,1,3)])
fruitind <- rast(read_mean_outputvalue(simulations[c], 
                                       years = c(1970:2000), model = "PHENOFIT", output_var = "FruitIndex")[,c(2,1,3)])
matind <- rast(read_mean_outputvalue(simulations[c],
                                     years = c(1970:2000), model = "PHENOFIT", output_var = "MaturationIndex")[,c(2,1,3)])
fitness <- rast(read_mean_outputvalue(simulations[c], 
                                     years = c(1970:2000), model = "PHENOFIT", output_var = "Fitness")[,c(2,1,3)])
  
indices <- c(surv, fruitind, matind)
  
presence <- rast(readRDS("D:/species/processed/fagus_sylvatica/fagus_sylvatica_presabs.rds"))
presence[presence == 0] <- NA
fitnessmask <- fitness
fitnessmask[fitnessmask >= thresholds[c]] <- NA
presence <- crop(presence, fitnessmask)
fitnessmask <- crop(fitnessmask, presence)
presencemask <- mask(presence, fitnessmask)
  
ggplot() +
    geom_spatraster(data = ifel(fitness >= 0, 1, NA), alpha = 0.2, show.legend = FALSE) +
    geom_spatraster(data = ifel(fitness >= thresholds[c], 1, NA), alpha = 0.2, show.legend = FALSE) +
    scale_fill_continuous(na.value = "transparent") +
    geom_spatraster_rgb(data = mask(crop(1-indices, presencemask), presencemask)*255) +
    theme_void()

indices_falseabsences <- as.data.frame(mask(crop(indices, presencemask), presencemask), xy = TRUE)
names(indices_falseabsences) <- c("lon", "lat", "surv", "fruitind", "matind")

df = indices_falseabsences
df$cluster = factor(kmeans(df[,c("surv", "fruitind", "matind")],3)$cluster)

p <- plot_ly(df, x=~surv, y=~fruitind, 
             z=~matind, color= ~I(rgb(1-surv, 1-fruitind, 1-matind))) %>%
  add_markers(size=1.5)
p

p <- plot_ly(df, x=~surv, y=~fruitind, 
             z=~matind, color=~cluster,
             colors = c("#95d2bc", "#fcaf96", "#afc2da")) %>%
  add_markers(size=1.5)
p

ggplot(data = df) +
  geom_spatraster(data = ifel(fitness >= 0, 1, NA), alpha = 0.2, show.legend = FALSE) +
  scale_fill_continuous(na.value = "transparent") +
  geom_point(aes(x = lon, y = lat, color = cluster), size = 0.4) +
  scale_color_manual(values = c("#95d2bc", "#fcaf96", "#afc2da")) +
  theme_void()

p1 <- ggplot(data = df) +
  geom_point(aes(x = surv, y = fruitind, color = cluster), alpha = 0.5) +
  scale_color_manual(values = c("#95d2bc", "#fcaf96", "#afc2da")) +
  theme_minimal() +
  theme(legend.position = "none")

p2 <- ggplot(data = df) +
  geom_point(aes(x = fruitind, y = matind, color = cluster), alpha = 0.5) +
  scale_color_manual(values = c("#95d2bc", "#fcaf96", "#afc2da")) +
  theme_minimal() +
  theme(legend.position = "none")

plot_grid(p1, p2, ncol = 2)

```


## subset7_rep5
```{r cmaes4}
c <- 5

surv <- rast(read_mean_outputvalue(simulations[c], 
                                   years = c(1970:2000), model = "PHENOFIT", output_var = "Survival")[,c(2,1,3)])
fruitind <- rast(read_mean_outputvalue(simulations[c], 
                                       years = c(1970:2000), model = "PHENOFIT", output_var = "FruitIndex")[,c(2,1,3)])
matind <- rast(read_mean_outputvalue(simulations[c],
                                     years = c(1970:2000), model = "PHENOFIT", output_var = "MaturationIndex")[,c(2,1,3)])
fitness <- rast(read_mean_outputvalue(simulations[c], 
                                     years = c(1970:2000), model = "PHENOFIT", output_var = "Fitness")[,c(2,1,3)])
  
indices <- c(surv, fruitind, matind)
  
presence <- rast(readRDS("D:/species/processed/fagus_sylvatica/fagus_sylvatica_presabs.rds"))
presence[presence == 0] <- NA
fitnessmask <- fitness
fitnessmask[fitnessmask >= thresholds[c]] <- NA
presence <- crop(presence, fitnessmask)
fitnessmask <- crop(fitnessmask, presence)
presencemask <- mask(presence, fitnessmask)
  
ggplot() +
    geom_spatraster(data = ifel(fitness >= 0, 1, NA), alpha = 0.2, show.legend = FALSE) +
    geom_spatraster(data = ifel(fitness >= thresholds[c], 1, NA), alpha = 0.2, show.legend = FALSE) +
    scale_fill_continuous(na.value = "transparent") +
    geom_spatraster_rgb(data = mask(crop(1-indices, presencemask), presencemask)*255) +
    theme_void()

indices_falseabsences <- as.data.frame(mask(crop(indices, presencemask), presencemask), xy = TRUE)
names(indices_falseabsences) <- c("lon", "lat", "surv", "fruitind", "matind")

df = indices_falseabsences
df$cluster = factor(kmeans(df[,c("surv", "fruitind", "matind")],3)$cluster)

p <- plot_ly(df, x=~surv, y=~fruitind, 
             z=~matind, color= ~I(rgb(1-surv, 1-fruitind, 1-matind))) %>%
  add_markers(size=1.5)
p

p <- plot_ly(df, x=~surv, y=~fruitind, 
             z=~matind, color=~cluster,
             colors = c("#95d2bc", "#fcaf96", "#afc2da")) %>%
  add_markers(size=1.5)
p

ggplot(data = df) +
  geom_spatraster(data = ifel(fitness >= 0, 1, NA), alpha = 0.2, show.legend = FALSE) +
  scale_fill_continuous(na.value = "transparent") +
  geom_point(aes(x = lon, y = lat, color = cluster), size = 0.4) +
  scale_color_manual(values = c("#95d2bc", "#fcaf96", "#afc2da")) +
  theme_void()

p1 <- ggplot(data = df) +
  geom_point(aes(x = surv, y = fruitind, color = cluster), alpha = 0.5) +
  scale_color_manual(values = c("#95d2bc", "#fcaf96", "#afc2da")) +
  theme_minimal() +
  theme(legend.position = "none")

p2 <- ggplot(data = df) +
  geom_point(aes(x = fruitind, y = matind, color = cluster), alpha = 0.5) +
  scale_color_manual(values = c("#95d2bc", "#fcaf96", "#afc2da")) +
  theme_minimal() +
  theme(legend.position = "none")

plot_grid(p1, p2, ncol = 2)

```

